spring:
  datasource:
    username: uctbb38zridfpsd3
    password: 8tBGaGhyjqLLXoaTfuUS 
    url: jdbc:mysql://b5p5ojtnhs5pd1xakcgy-mysql.services.clever-cloud.com:3306/b5p5ojtnhs5pd1xakcgy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: www.indrajit55@gmail.com
    password: rsygyoxhxdqwxpyz
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
springdoc:
  swagger-ui:
    csrf:
      enabled: true
